### ISSUE TITLE
Latest 0.22 Freetube is damaged and can't be opened

### ISSUE THREAD

**Issue by darkfires** [PikachuEXE/homebrew-FreeTube#45] opened 2024-10-31 18:34 UTC
Here's a screenshot of what happens
https://i.imgur.com/xqrIvOd.png

Any ideas?

**Comment by darkfires** [comment] 2024-10-31 18:38
If I go into the /Applications/FreeTube.app/Contents/MacOS and run ./FreeTube it will run but I can't open it via the icon at all and there's nothing in privacy and security to open it anyway

**Comment by PikachuEXE** [comment] 2024-10-31 22:17
I have just tested `brew install --no-quarantine pikachuexe/freetube/pikachuexe-freetube` with MacOS 14.7
The app can be opened on my machine
Please provide your installation steps & MacOS versions

Also maybe try downloading `dmg` manually and run `/usr/bin/xattr -dr com.apple.quarantine <path/to/file>`

**Comment by wtimme** [comment] 2024-11-09 18:43
I can confirm that for me, too, macOS reported that Freetube is damaged and cannot be opened. I have had the app installed on my machine for quite a while now, and never had an issue up until recently.

Uninstalling and re-installing the app via Homebrew (using `brew install --no-quarantine pikachuexe/freetube/pikachuexe-freetube`) resolved the issue on my end.

FWIW, I'm on macOS 14.7.1.

**Comment by PikachuEXE** [comment] 2024-11-09 22:55
How did you install/update that makes it from working to not working???

**Comment by wtimme** [comment] 2024-11-10 15:00
So thanks to your cask, I rely solely on Homebrew when updating FreeTube.

Maybe this issue can be reproduced by installing an older version of the cask via Homebrew, and then using `homebrew upgrade` to update it.

**Comment by PikachuEXE** [comment] 2024-11-11 01:15
Could be a Homebrew issue or we need to make some changes to the cask
https://github.com/Homebrew/brew/issues/17979
No idea yet need more time reseaching

**Comment by toobuntu** [comment] 2024-11-11 02:21
It rather looks like user error by not having consistently used the `--no-quarantine` option to install and upgrade. Perhaps the README should be explicit that this option is needed not only on `brew install`, but also on every subsequent `brew reinstall` and `brew upgrade` involving the cask from this tap.

**Comment by darkfires** [comment] 2024-11-11 02:35
I can confirm the --no-quarantine flag on reinstall fixes the problem for me.  Thanks for your efforts! :)

**Comment by PikachuEXE** [comment] 2024-11-11 02:37
Would adding something like this into README seem enough for you guys? :)
![image](https://github.com/user-attachments/assets/30b367d6-7a39-42bf-aa9f-156fd48ba5b4)

**Comment by toobuntu** [comment] 2024-11-11 03:02
You might want to add for the upgrade case that `brew upgrade --no-quarantine` on its own will also work even without specifying this cask (`brew upgrade --no-quarantine pikachuexe/freetube/pikachuexe-freetube`), but that doing so would mean that the quarantine removal would also affect every other cask being upgraded on that run of the command. That is an easier workflow but does come with a security implication. On the other hand, specifying this cask means that only this cask will be upgraded with that particular run of the command.

**Comment by PikachuEXE** [comment] 2024-11-11 03:05
Add a Security Note below?
![image](https://github.com/user-attachments/assets/78538957-1f61-4d38-82a8-a857889aa8da)

**Comment by toobuntu** [comment] 2024-11-11 03:11
LGTM, with one nitpick in the security note.
Suggested change:

```bash
- it upgrades all installed cask
+ it upgrades all installed casks
```

**Comment by PikachuEXE** [comment] 2024-11-11 03:29
https://github.com/PikachuEXE/homebrew-FreeTube/commit/f010680eb0ece34386d67061d0b405e2611264a1

**Comment by PikachuEXE** [comment] 2024-11-12 00:17
Closing since README updated
Feel free to reopen if any issue left

**Closed by PikachuEXE** 2024-11-12 00:17 UTC

**Comment by PikachuEXE** [comment] 2025-11-30 12:07
https://github.com/PikachuEXE/homebrew-FreeTube/tree/v0.23.12-beta?tab=readme-ov-file#freetubes-homebrew-tap-for-apple-silicon

> Warning: macOS's Gatekeeper has been disabled for this Cask

> According to the vendor, the Gatekeeper quarantine attribute breaks the app and needs to be removed. This Cask automatically removes the quarantine attribute. No further action is required.
